project:
  type: website

website:
  title: "Portfolio Nicolas Luna"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: CV.qmd
        text: CV
      - href: Projects.qmd
        text: Projects
      - href: Skills.qmd
        text: Skills

format:
  html:
    theme:
      - flatly
      - brand
    css: styles.css
    toc: true

editor: visual

deploy:
  provider: gh-pages
